// apps/webapp/src/modules/onboarding/ui/card.svelte
<script lang="ts">
	let { image, title, description } = $props<{
		image: string;
		title: string;
		description: string;
	}>();
</script>

<div
	class="w-full mx-auto px-6 py-10 rounded-2xl overflow-hidden bg-white/50 dark:bg-white/5 border border-white/40 dark:border-white/10 shadow-sm flex flex-col items-center justify-center mb-8 relative select-none"
>
	<img
		class="w-full max-w-[320px] aspect-square bg-center bg-contain bg-no-repeat"
		src={image}
		alt={title}
	/>
</div>
<div class="select-none">
	<h1
		class="text-foreground mb-2 dark:text-white text-center tracking-tight text-[28px] md:text-[32px] font-bold leading-tight"
	>
		{title}
	</h1>
	<p
		class="text-muted-foreground px-2 dark:text-[#a3c2af] text-base text-center font-medium leading-relaxed"
	>
		{description}
	</p>
</div>

// packages/rune/src/components/ui/card.tsx
import * as React from 'react';

import { cn } from '../../lib/utils';

export function Card({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={cn(
        'rounded-2xl border border-[var(--color-border)] bg-[var(--color-card)] text-[var(--color-card-foreground)] shadow-sm',
        className,
      )}
      {...props}
    />
  );
}

export function CardHeader({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn('flex flex-col gap-1.5 p-4', className)} {...props} />;
}

export function CardTitle({
  className,
  ...props
}: React.HTMLAttributes<HTMLHeadingElement>) {
  return (
    <h3
      className={cn('text-lg font-bold leading-none tracking-tight', className)}
      {...props}
    />
  );
}

export function CardDescription({
  className,
  ...props
}: React.HTMLAttributes<HTMLParagraphElement>) {
  return (
    <p
      className={cn('text-sm text-[var(--color-muted-foreground)]', className)}
      {...props}
    />
  );
}

export function CardContent({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn('p-4 pt-0', className)} {...props} />;
}

export function CardFooter({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div className={cn('flex items-center p-4 pt-0', className)} {...props} />
  );
}
