// packages/ui-kit/src/lib/components/ui/select/select.svelte
<script lang="ts" generics="T">
	import ChevronDownIcon from '@lucide/svelte/icons/chevron-down';
	import { Select as SelectPrimitive } from 'bits-ui';
	import { cn } from '$lib/utils';
	import type { SelectProps, SelectSize } from './types';

	const SELECT_TRIGGER_SIZES: Record<
		SelectSize,
		{ height: string; text: string; icon: string; padding: string }
	> = {
		sm: {
			height: 'h-10',
			text: 'text-sm',
			icon: 'size-4',
			padding: 'px-3'
		},
		default: {
			height: 'h-12',
			text: 'text-[15px]',
			icon: 'size-4',
			padding: 'px-4'
		},
		lg: {
			height: 'h-14',
			text: 'text-base',
			icon: 'size-5',
			padding: 'px-4'
		}
	};

	let {
		items,
		isChecked,
		onSelect,
		getItemKey,
		isItemDisabled,
		label,
		item,
		placeholder,
		disabled = false,
		open = $bindable(false),
		size = 'default',
		class: className,
		contentClass,
		align = 'start',
		sideOffset = 8
	}: SelectProps<T> = $props();

	const triggerSize = $derived(SELECT_TRIGGER_SIZES[size]);
	const selectedItem = $derived(items.find(isChecked));
	const selectedValue = $derived(
		selectedItem ? resolveItemKey({ item: selectedItem, index: items.indexOf(selectedItem) }) : undefined
	);

	function resolveItemKey(props: { item: T; index: number }) {
		return getItemKey?.(props.item) ?? String(props.index);
	}

	function handleValueChange(value: string) {
		const nextItem = items.find(
			(entry, index) => resolveItemKey({ item: entry, index }) === value
		);

		if (nextItem) {
			onSelect(nextItem);
		}
	}
</script>

<SelectPrimitive.Root
	type="single"
	value={selectedValue}
	onValueChange={handleValueChange}
	bind:open
	{disabled}
>
	<SelectPrimitive.Trigger>
		{#snippet child({ props })}
			<button
				{...props}
				type="button"
				data-slot="select-trigger"
				class={cn(
					'inline-flex w-full min-w-0 items-center justify-between gap-2 rounded-[12px] border border-[#E2E8F0] bg-white text-left font-medium text-[#0F172A] outline-none transition-colors',
					'focus-visible:ring-2 focus-visible:ring-primary/30 disabled:cursor-not-allowed disabled:opacity-50',
					triggerSize.height,
					triggerSize.text,
					triggerSize.padding,
					className
				)}
			>
				<span class="flex min-w-0 flex-1 items-center">
					{#if selectedItem}
						{@render label({ selected: selectedItem })}
					{:else if placeholder}
						<span class="truncate text-slate-400">{placeholder}</span>
					{:else}
						{@render label({ selected: undefined })}
					{/if}
				</span>
				<ChevronDownIcon
					class={cn('shrink-0 text-slate-400 transition-transform', triggerSize.icon, open && 'rotate-180')}
				/>
			</button>
		{/snippet}
	</SelectPrimitive.Trigger>

	<SelectPrimitive.Portal>
		<SelectPrimitive.Content
			data-slot="select-content"
			{align}
			{sideOffset}
			class={cn(
				'z-50 max-h-60 w-[var(--bits-select-anchor-width)] overflow-hidden rounded-[12px] border border-[#E2E8F0] bg-white p-1 shadow-md',
				'data-open:animate-in data-closed:animate-out data-closed:fade-out-0 data-open:fade-in-0 data-closed:zoom-out-95 data-open:zoom-in-95',
				contentClass
			)}
		>
			{#each items as entry, index (resolveItemKey({ item: entry, index }))}
				{@const itemKey = resolveItemKey({ item: entry, index })}
				{@const itemDisabled = isItemDisabled?.(entry) ?? false}

				<SelectPrimitive.Item value={itemKey} disabled={itemDisabled}>
					{#snippet child({ props, selected, highlighted })}
						<div
							{...props}
							class={cn(
								'relative flex w-full cursor-default select-none items-center rounded-[8px] px-3 py-2.5 outline-none transition-colors',
								highlighted && 'bg-[#F8FAFC]',
								selected && 'bg-primary/10',
								itemDisabled && 'pointer-events-none opacity-50'
							)}
						>
							{@render item({ item: entry, checked: selected, highlighted })}
						</div>
					{/snippet}
				</SelectPrimitive.Item>
			{/each}
		</SelectPrimitive.Content>
	</SelectPrimitive.Portal>
</SelectPrimitive.Root>

// packages/rune/src/components/ui/select.tsx
import * as SelectPrimitive from '@radix-ui/react-select';
import { Check, ChevronDown } from 'lucide-react';
import * as React from 'react';

import { cn } from '../../lib/utils';

export const Select = SelectPrimitive.Root;
export const SelectValue = SelectPrimitive.Value;

export const SelectTrigger = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Trigger>
>(({ className, children, ...props }, ref) => (
  <SelectPrimitive.Trigger
    ref={ref}
    className={cn(
      'group flex h-12 w-full items-center justify-between rounded-xl border border-transparent bg-[var(--color-input)] px-3.5 py-2 text-base transition-colors focus:outline-none focus:ring-2 focus:ring-[var(--color-ring)] disabled:cursor-not-allowed disabled:opacity-50 [&>span]:line-clamp-1',
      className,
    )}
    {...props}
  >
    {children}
    <SelectPrimitive.Icon asChild>
      <ChevronDown className="h-4 w-4 opacity-50 transition-transform duration-200 group-data-[state=open]:rotate-180" />
    </SelectPrimitive.Icon>
  </SelectPrimitive.Trigger>
));
SelectTrigger.displayName = SelectPrimitive.Trigger.displayName;

export const SelectContent = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Content>
>(({ className, children, position = 'popper', ...props }, ref) => (
  <SelectPrimitive.Portal>
    <SelectPrimitive.Content
      ref={ref}
      className={cn(
        'relative z-50 max-h-72 min-w-[8rem] overflow-hidden rounded-xl border bg-white text-slate-900 shadow-md',
        'data-[state=open]:animate-in data-[state=closed]:animate-out',
        'data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0',
        'data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95',
        'data-[side=bottom]:slide-in-from-top-2 data-[side=top]:slide-in-from-bottom-2',
        'duration-150',
        position === 'popper' &&
          'data-[side=bottom]:translate-y-1 data-[side=top]:-translate-y-1',
        className,
      )}
      position={position}
      {...props}
    >
      <SelectPrimitive.Viewport
        className={cn(
          'p-1',
          position === 'popper' &&
            'h-[var(--radix-select-trigger-height)] w-full min-w-[var(--radix-select-trigger-width)]',
        )}
      >
        {children}
      </SelectPrimitive.Viewport>
    </SelectPrimitive.Content>
  </SelectPrimitive.Portal>
));
SelectContent.displayName = SelectPrimitive.Content.displayName;

export const SelectItem = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Item>
>(({ className, children, ...props }, ref) => (
  <SelectPrimitive.Item
    ref={ref}
    className={cn(
      'relative flex w-full cursor-default select-none items-center rounded-lg py-2.5 pl-8 pr-2 text-sm outline-none transition-colors focus:bg-slate-100 data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
      className,
    )}
    {...props}
  >
    <span className="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
      <SelectPrimitive.ItemIndicator>
        <Check className="h-4 w-4" />
      </SelectPrimitive.ItemIndicator>
    </span>
    <SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText>
  </SelectPrimitive.Item>
));
SelectItem.displayName = SelectPrimitive.Item.displayName;
